// src/pages/TodoManager.vue
<template>
  <div>
    <div class="page-header">
      <div>
        <a-typography-title :level="3" :style="{ color: 'var(--text-primary)', margin: 0 }">
          <CheckSquareOutlined style="margin-right: 10px;" />
          待办事项
        </a-typography-title>
        <a-typography-text :style="{ color: 'var(--text-secondary)' }">
          管理你的任务和计划
        </a-typography-text>
      </div>
      <a-button type="primary" @click="modalOpen = true">
        <template #icon><PlusOutlined /></template>
        新建待办
      </a-button>
    </div>

    <a-card class="wb-card quick-card">
      <div class="quick-add">
        <a-input
          v-model:value="quickInput"
          placeholder="快速添加今日待办，按回车确认..."
          @pressEnter="handleAddQuick"
        >
          <template #prefix><PlusOutlined style="color: var(--text-muted);" /></template>
        </a-input>
        <a-button type="primary" @click="handleAddQuick">添加</a-button>
      </div>
    </a-card>

    <div class="toolbar">
      <a-segmented v-model:value="viewMode" :options="viewOptions" />
      <a-select
        v-if="viewMode === 'list'"
        v-model:value="filter"
        :options="filterOptions"
        style="width: 120px;"
      />
      <a-typography-text class="toolbar-meta">共 {{ filteredTodos.length }} 条</a-typography-text>
    </div>

    <a-row :gutter="16">
      <a-col v-if="viewMode === 'calendar'" :xs="24" :md="10">
        <a-card class="wb-card" style="margin-bottom: 16px;">
          <a-calendar v-model:value="selectedDate" :fullscreen="false">
            <template #dateCellRender="{ current }">
              <div v-if="todosByDate[current.format('YYYY-MM-DD')]" class="date-badge-wrap">
                <a-badge :count="todosByDate[current.format('YYYY-MM-DD')]" color="var(--accent)" />
              </div>
            </template>
          </a-calendar>
        </a-card>
      </a-col>

      <a-col :xs="24" :md="viewMode === 'calendar' ? 14 : 24">
        <a-card class="wb-card">
          <template v-if="viewMode === 'calendar'" #title>
            <span style="color: var(--text-primary);">{{ selectedDate.format('M月D日') }} 的待办</span>
          </template>

          <div v-if="filteredTodos.length === 0" style="padding: 40px;">
            <a-empty description="暂无待办事项" />
          </div>

          <div v-else class="todo-list">
            <div v-for="todo in filteredTodos" :key="todo.id" class="todo-item" :class="{ done: todo.done }">
              <a-checkbox :checked="todo.done" @change="toggleDone(todo.id)" />
              <span class="priority-chip" :class="todo.priority">
                {{ priorityMap[todo.priority]?.label || '中优先' }}
              </span>
              <div class="todo-main">
                <a-typography-text :delete="todo.done" :style="{ color: 'var(--text-primary)' }">
                  {{ todo.title }}
                </a-typography-text>
                <a-typography-text class="todo-time">
                  <CalendarOutlined style="margin-right: 4px;" />
                  {{ todo.date }}
                  <span v-if="todo.time" style="margin-left: 8px;">
                    <ClockCircleOutlined style="margin-right: 4px;" />
                    {{ todo.time }}
                  </span>
                </a-typography-text>
              </div>
              <button class="icon-button danger" @click="handleDelete(todo.id)">
                <DeleteOutlined />
              </button>
            </div>
          </div>
        </a-card>
      </a-col>
    </a-row>

    <a-modal
      :open="modalOpen"
      title="新建待办"
      ok-text="添加"
      cancel-text="取消"
      :width="480"
      @ok="handleSave"
      @cancel="closeModal"
    >
      <div class="modal-form">
        <label class="field-label">待办内容</label>
        <a-input v-model:value="form.title" placeholder="要做什么？" />

        <div class="row-fields">
          <div>
            <label class="field-label">日期</label>
            <a-date-picker v-model:value="form.date" style="width: 100%;" />
          </div>
          <div>
            <label class="field-label">时间</label>
            <a-time-picker v-model:value="form.time" format="HH:mm" style="width: 100%;" />
          </div>
        </div>

        <label class="field-label">优先级</label>
        <a-select v-model:value="form.priority" :options="priorityOptions" />
      </div>
    </a-modal>
  </div>
</template>

<script setup>
import { computed, reactive, ref } from 'vue';
import dayjs from 'dayjs';
import { message } from 'ant-design-vue';
import { v4 as uuid } from 'uuid';
import { usePersistentState } from '../store/useStore';
import {
  CalendarOutlined,
  CheckSquareOutlined,
  ClockCircleOutlined,
  DeleteOutlined,
  PlusOutlined,
} from '@ant-design/icons-vue';

const priorityOptions = [
  { label: '高优先', value: 'high', color: 'red' },
  { label: '中优先', value: 'medium', color: 'orange' },
  { label: '低优先', value: 'low', color: 'blue' },
];

const priorityMap = Object.fromEntries(priorityOptions.map((item) => [item.value, item]));

const viewOptions = [
  { label: '列表', value: 'list' },
  { label: '日历', value: 'calendar' },
];

const filterOptions = [
  { label: '全部', value: 'all' },
  { label: '今日', value: 'today' },
  { label: '未完成', value: 'pending' },
  { label: '已完成', value: 'done' },
  { label: '已过期', value: 'overdue' },
];

const emptyForm = () => ({
  title: '',
  date: null,
  time: null,
  priority: 'medium',
});

const { state: todos } = usePersistentState('todos', []);
const modalOpen = ref(false);
const viewMode = ref('list');
const selectedDate = ref(dayjs());
const filter = ref('all');
const quickInput = ref('');
const form = reactive(emptyForm());

const today = computed(() => dayjs().format('YYYY-MM-DD'));

const filteredTodos = computed(() => {
  let list = [...todos.value];

  if (viewMode.value === 'calendar') {
    const dateStr = selectedDate.value.format('YYYY-MM-DD');
    list = list.filter((item) => item.date === dateStr);
  }

  if (filter.value === 'today') list = list.filter((item) => item.date === today.value);
  else if (filter.value === 'pending') list = list.filter((item) => !item.done);
  else if (filter.value === 'done') list = list.filter((item) => item.done);
  else if (filter.value === 'overdue') list = list.filter((item) => !item.done && item.date < today.value);

  const order = { high: 0, medium: 1, low: 2 };
  return list.sort((a, b) => {
    if (a.done !== b.done) return a.done ? 1 : -1;
    return (order[a.priority] ?? 1) - (order[b.priority] ?? 1);
  });
});

const todosByDate = computed(() => {
  const map = {};
  todos.value.forEach((item) => {
    if (!item.done) {
      map[item.date] = (map[item.date] || 0) + 1;
    }
  });
  return map;
});

function resetForm() {
  Object.assign(form, emptyForm());
}

function handleAddQuick() {
  if (!quickInput.value.trim()) return;

  todos.value = [
    {
      id: uuid(),
      title: quickInput.value.trim(),
      date: today.value,
      time: '',
      priority: 'medium',
      done: false,
      createdAt: new Date().toISOString(),
    },
    ...todos.value,
  ];
  quickInput.value = '';
  message.success('已添加到今日待办');
}

function handleSave() {
  if (!form.title.trim()) return message.error('请输入待办内容');

  todos.value = [
    {
      id: uuid(),
      title: form.title.trim(),
      date: form.date ? form.date.format('YYYY-MM-DD') : today.value,
      time: form.time ? form.time.format('HH:mm') : '',
      priority: form.priority || 'medium',
      done: false,
      createdAt: new Date().toISOString(),
    },
    ...todos.value,
  ];

  message.success('已添加');
  closeModal();
}

function closeModal() {
  modalOpen.value = false;
  resetForm();
}

function toggleDone(id) {
  todos.value = todos.value.map((item) => (item.id === id ? { ...item, done: !item.done } : item));
}

function handleDelete(id) {
  todos.value = todos.value.filter((item) => item.id !== id);
  message.success('已删除');
}
</script>

<style scoped>
.page-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 24px;
}

.wb-card {
  background: var(--bg-card);
  border: 1px solid var(--border);
  border-radius: var(--radius);
}

.quick-card {
  margin-bottom: 16px;
}

.quick-add {
  display: flex;
  gap: 12px;
}

.toolbar {
  display: flex;
  align-items: center;
  gap: 12px;
  margin-bottom: 16px;
  flex-wrap: wrap;
}

.toolbar-meta {
  margin-left: auto;
  color: var(--text-muted);
  font-size: 13px;
}

.todo-list {
  display: grid;
}

.todo-item {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 12px 16px;
  border-bottom: 1px solid var(--border);
}

.todo-item.done {
  opacity: 0.5;
}

.todo-main {
  flex: 1;
}

.todo-time {
  display: block;
  color: var(--text-muted);
  font-size: 12px;
}

.priority-chip {
  min-width: 60px;
  padding: 4px 8px;
  border-radius: 999px;
  text-align: center;
  font-size: 12px;
  font-weight: 600;
}

.priority-chip.high {
  background: rgba(255, 107, 107, 0.15);
  color: #ff6b6b;
}

.priority-chip.medium {
  background: rgba(252, 196, 25, 0.14);
  color: #fcc419;
}

.priority-chip.low {
  background: rgba(116, 185, 255, 0.14);
  color: #74b9ff;
}

.modal-form {
  display: grid;
  gap: 10px;
  margin-top: 16px;
}

.row-fields {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 12px;
}

.field-label {
  display: block;
  color: var(--text-secondary);
  font-size: 13px;
  margin-bottom: 6px;
}

.icon-button.danger {
  color: var(--danger);
}

.date-badge-wrap {
  display: flex;
  justify-content: center;
}
</style>

// src/pages/TodoManager.jsx
import React, { useState, useMemo } from 'react';
import {
  Card,
  Button,
  Input,
  Modal,
  Form,
  Select,
  Space,
  Typography,
  Tag,
  Checkbox,
  DatePicker,
  TimePicker,
  Calendar,
  Badge,
  Tooltip,
  message,
  Popconfirm,
  Empty,
  Segmented,
  Row,
  Col,
} from 'antd';
import {
  PlusOutlined,
  DeleteOutlined,
  CheckSquareOutlined,
  CalendarOutlined,
  UnorderedListOutlined,
  ClockCircleOutlined,
  FilterOutlined,
} from '@ant-design/icons';
import dayjs from 'dayjs';
import { v4 as uuid } from 'uuid';
import { usePersistentState } from '../store/useStore';

const { Title, Text } = Typography;

const PRIORITIES = [
  { label: '高优先', value: 'high', color: 'red' },
  { label: '中优先', value: 'medium', color: 'orange' },
  { label: '低优先', value: 'low', color: 'blue' },
];

const priorityMap = Object.fromEntries(PRIORITIES.map((p) => [p.value, p]));

export default function TodoManager() {
  const [todos, setTodos] = usePersistentState('todos', []);
  const [modalOpen, setModalOpen] = useState(false);
  const [viewMode, setViewMode] = useState('list');
  const [selectedDate, setSelectedDate] = useState(dayjs());
  const [filter, setFilter] = useState('all');
  const [quickInput, setQuickInput] = useState('');
  const [form] = Form.useForm();

  const today = dayjs().format('YYYY-MM-DD');

  const handleAddQuick = () => {
    if (!quickInput.trim()) return;
    setTodos((prev) => [
      {
        id: uuid(),
        title: quickInput.trim(),
        date: today,
        time: '',
        priority: 'medium',
        done: false,
        createdAt: new Date().toISOString(),
      },
      ...prev,
    ]);
    setQuickInput('');
    message.success('已添加到今日待办');
  };

  const handleSave = () => {
    form.validateFields().then((values) => {
      setTodos((prev) => [
        {
          id: uuid(),
          title: values.title,
          date: values.date ? values.date.format('YYYY-MM-DD') : today,
          time: values.time ? values.time.format('HH:mm') : '',
          priority: values.priority || 'medium',
          done: false,
          createdAt: new Date().toISOString(),
        },
        ...prev,
      ]);
      message.success('已添加');
      setModalOpen(false);
      form.resetFields();
    });
  };

  const toggleDone = (id) => {
    setTodos((prev) => prev.map((t) => (t.id === id ? { ...t, done: !t.done } : t)));
  };

  const handleDelete = (id) => {
    setTodos((prev) => prev.filter((t) => t.id !== id));
  };

  const filteredTodos = useMemo(() => {
    let list = [...todos];
    if (viewMode === 'calendar') {
      const dateStr = selectedDate.format('YYYY-MM-DD');
      list = list.filter((t) => t.date === dateStr);
    }
    if (filter === 'today') list = list.filter((t) => t.date === today);
    else if (filter === 'pending') list = list.filter((t) => !t.done);
    else if (filter === 'done') list = list.filter((t) => t.done);
    else if (filter === 'overdue') list = list.filter((t) => !t.done && t.date < today);

    list.sort((a, b) => {
      if (a.done !== b.done) return a.done ? 1 : -1;
      const pOrder = { high: 0, medium: 1, low: 2 };
      return (pOrder[a.priority] ?? 1) - (pOrder[b.priority] ?? 1);
    });
    return list;
  }, [todos, viewMode, selectedDate, filter, today]);

  const todosByDate = useMemo(() => {
    const map = {};
    todos.forEach((t) => {
      if (!t.done) {
        map[t.date] = (map[t.date] || 0) + 1;
      }
    });
    return map;
  }, [todos]);

  const dateCellRender = (date) => {
    const dateStr = date.format('YYYY-MM-DD');
    const count = todosByDate[dateStr];
    if (!count) return null;
    return (
      <div style={{ textAlign: 'center' }}>
        <Badge count={count} size="small" color="var(--accent)" />
      </div>
    );
  };

  const TodoItem = ({ todo }) => (
    <div
      style={{
        display: 'flex',
        alignItems: 'center',
        padding: '12px 16px',
        borderBottom: '1px solid var(--border)',
        opacity: todo.done ? 0.5 : 1,
        gap: 12,
      }}
    >
      <Checkbox checked={todo.done} onChange={() => toggleDone(todo.id)} />
      <Tag color={priorityMap[todo.priority]?.color || 'blue'} style={{ minWidth: 52, textAlign: 'center' }}>
        {priorityMap[todo.priority]?.label || '中'}
      </Tag>
      <div style={{ flex: 1 }}>
        <Text
          style={{
            color: 'var(--text-primary)',
            textDecoration: todo.done ? 'line-through' : 'none',
          }}
        >
          {todo.title}
        </Text>
        <div>
          <Text style={{ color: 'var(--text-muted)', fontSize: 12 }}>
            <CalendarOutlined style={{ marginRight: 4 }} />
            {todo.date}
            {todo.time && (
              <span style={{ marginLeft: 8 }}>
                <ClockCircleOutlined style={{ marginRight: 4 }} />
                {todo.time}
              </span>
            )}
          </Text>
        </div>
      </div>
      <Popconfirm title="删除此待办？" onConfirm={() => handleDelete(todo.id)}>
        <Button type="text" danger icon={<DeleteOutlined />} size="small" />
      </Popconfirm>
    </div>
  );

  return (
    <div>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 24 }}>
        <div>
          <Title level={3} style={{ color: 'var(--text-primary)', margin: 0 }}>
            <CheckSquareOutlined style={{ marginRight: 10 }} />
            待办事项
          </Title>
          <Text style={{ color: 'var(--text-secondary)' }}>管理你的任务和计划</Text>
        </div>
        <Button type="primary" icon={<PlusOutlined />} onClick={() => setModalOpen(true)}>
          新建待办
        </Button>
      </div>

      {/* Quick add */}
      <Card
        style={{
          background: 'var(--bg-card)',
          border: '1px solid var(--border)',
          borderRadius: 'var(--radius)',
          marginBottom: 16,
        }}
        styles={{ body: { padding: '12px 16px' } }}
      >
        <Space.Compact style={{ width: '100%' }}>
          <Input
            placeholder="快速添加今日待办，按回车确认..."
            value={quickInput}
            onChange={(e) => setQuickInput(e.target.value)}
            onPressEnter={handleAddQuick}
            prefix={<PlusOutlined style={{ color: 'var(--text-muted)' }} />}
          />
          <Button type="primary" onClick={handleAddQuick}>
            添加
          </Button>
        </Space.Compact>
      </Card>

      <div style={{ display: 'flex', gap: 12, marginBottom: 16, flexWrap: 'wrap', alignItems: 'center' }}>
        <Segmented
          value={viewMode}
          onChange={setViewMode}
          options={[
            { label: <span><UnorderedListOutlined /> 列表</span>, value: 'list' },
            { label: <span><CalendarOutlined /> 日历</span>, value: 'calendar' },
          ]}
        />
        {viewMode === 'list' && (
          <Select
            value={filter}
            onChange={setFilter}
            style={{ width: 120 }}
            prefix={<FilterOutlined />}
            options={[
              { label: '全部', value: 'all' },
              { label: '今日', value: 'today' },
              { label: '未完成', value: 'pending' },
              { label: '已完成', value: 'done' },
              { label: '已过期', value: 'overdue' },
            ]}
          />
        )}
        <Text style={{ color: 'var(--text-muted)', marginLeft: 'auto', fontSize: 13 }}>
          共 {filteredTodos.length} 条
        </Text>
      </div>

      <Row gutter={16}>
        {viewMode === 'calendar' && (
          <Col xs={24} md={10}>
            <Card
              style={{
                background: 'var(--bg-card)',
                border: '1px solid var(--border)',
                borderRadius: 'var(--radius)',
                marginBottom: 16,
              }}
            >
              <Calendar
                fullscreen={false}
                value={selectedDate}
                onSelect={(d) => setSelectedDate(d)}
                cellRender={(date, info) => {
                  if (info.type === 'date') return dateCellRender(date);
                  return null;
                }}
              />
            </Card>
          </Col>
        )}
        <Col xs={24} md={viewMode === 'calendar' ? 14 : 24}>
          <Card
            title={
              viewMode === 'calendar' ? (
                <span style={{ color: 'var(--text-primary)' }}>
                  {selectedDate.format('M月D日')} 的待办
                </span>
              ) : null
            }
            style={{
              background: 'var(--bg-card)',
              border: '1px solid var(--border)',
              borderRadius: 'var(--radius)',
            }}
            styles={{ body: { padding: 0 } }}
          >
            {filteredTodos.length === 0 ? (
              <div style={{ padding: 40 }}>
                <Empty description="暂无待办事项" image={Empty.PRESENTED_IMAGE_SIMPLE} />
              </div>
            ) : (
              filteredTodos.map((todo) => <TodoItem key={todo.id} todo={todo} />)
            )}
          </Card>
        </Col>
      </Row>

      <Modal
        title="新建待办"
        open={modalOpen}
        onOk={handleSave}
        onCancel={() => { setModalOpen(false); form.resetFields(); }}
        okText="添加"
        cancelText="取消"
        width={480}
        destroyOnClose
      >
        <Form form={form} layout="vertical" style={{ marginTop: 16 }}>
          <Form.Item name="title" label="待办内容" rules={[{ required: true, message: '请输入待办内容' }]}>
            <Input placeholder="要做什么？" />
          </Form.Item>
          <Row gutter={12}>
            <Col span={12}>
              <Form.Item name="date" label="日期">
                <DatePicker style={{ width: '100%' }} placeholder="选择日期" />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item name="time" label="时间">
                <TimePicker style={{ width: '100%' }} format="HH:mm" placeholder="选择时间" />
              </Form.Item>
            </Col>
          </Row>
          <Form.Item name="priority" label="优先级" initialValue="medium">
            <Select options={PRIORITIES} />
          </Form.Item>
        </Form>
      </Modal>
    </div>
  );
}
